# Generated by Django 4.2.9 on 2024-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
